# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dave Newman's Blog
email: newman.de@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about software development, system administration,
  and the exploration of technology. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dasnewman
github_username:  davidnewman

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [ "no_intra_emphasis", "fenced_code_blocks", "tables"]
